name: Static Content Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Detect changes
        id: changes
        env:
          CHANGELOG: changes.txt
        run: |
          make changelog
          echo "js=$(grep JS changes.txt | cut -d= -f2)" >> $GITHUB_OUTPUT
          echo "css=$(grep CSS changes.txt | cut -d= -f2)" >> $GITHUB_OUTPUT
          echo "bin=$(grep BIN changes.txt | cut -d= -f2)" >> $GITHUB_OUTPUT

      - name: Compute version
        id: semver
        if: steps.changes.outputs.css == 'true' or  steps.changes.outputs.js == 'true'
        env:
          JS_CHANGED: ${{ steps.changes.outputs.js }}
          CSS_CHANGED: ${{ steps.changes.outputs.css }}
        run: |
          TAG=$(make print-version)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Copy versioned content
        if: steps.changes.outputs.css == 'true' or  steps.changes.outputs.js == 'true'
        env:
          TAG: ${{ steps.semver.outputs.tag }}
          JS_CHANGED: ${{ steps.changes.outputs.js }}
          CSS_CHANGED: ${{ steps.changes.outputs.css }}
        run: |
          make stage-version

      - name: Bump version and push tag
        if: (steps.changes.outputs.css == 'true' ||  steps.changes.outputs.js == 'true')
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.tag }}

      - name: Commit JS & CSS
        if: github.ref == 'refs/heads/main' && (steps.changes.outputs.css == 'true' ||  steps.changes.outputs.js == 'true')
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
              js/${{ steps.semver.outputs.tag }}/**
              css/${{ steps.semver.outputs.tag }}/**
            commit-msg: "auto-release ${{ steps.semver.outputs.tag }}"
            github-token: ${{ secrets.GH_TOKEN }}
            allow-removing: true

      # ======================================================
      # Publish LATEST (push main)
      # ======================================================

      - name: Upload latest JS
        if: github.event_name == 'push' && steps.changes.outputs.js == 'true'
        uses: ryand56/r2-upload-action@v1
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_KEY }}
          r2-bucket: static
          source-dir: js/_
          destination-dir: static/_/js

      - name: Upload latest CSS
        if: github.event_name == 'push' && steps.changes.outputs.css == 'true'
        uses: ryand56/r2-upload-action@v1
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_KEY }}
          r2-bucket: static
          source-dir: css/_
          destination-dir: static/_/css

      - name: Upload latest BIN
        if: github.event_name == 'push' && steps.changes.outputs.bin == 'true'
        uses: ryand56/r2-upload-action@v1
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_KEY }}
          r2-bucket: static
          source-dir: bin/_
          destination-dir: static/bin/_

      # ======================================================
      # Publish VERSIONED (PR)
      # ======================================================

      - name: Upload versioned JS
        if: github.ref == 'refs/heads/main' && steps.changes.outputs.js == 'true'
        uses: ryand56/r2-upload-action@v1
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_KEY }}
          r2-bucket: static
          source-dir: js/${{ steps.semver.outputs.tag }}
          destination-dir: static/${{ steps.semver.outputs.tag }}/js

      - name: Upload versioned CSS
        if: github.ref == 'refs/heads/main' && steps.changes.outputs.css == 'true'
        uses: ryand56/r2-upload-action@v1
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_KEY }}
          r2-bucket: static
          source-dir: css/${{ steps.semver.outputs.tag }}
          destination-dir: static/${{ steps.semver.outputs.tag }}/css

      - name: Upload BIN (always latest)
        if: github.ref == 'refs/heads/main' && steps.changes.outputs.bin == 'true'
        uses: ryand56/r2-upload-action@v1
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_KEY }}
          r2-bucket: static
          source-dir: bin/_
          destination-dir: static/bin
